export const GET_PRODUCT_DATA = 'GET_PRODUCT_DATA';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';
